server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            preLogger: true
            postLogger: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Forwarded-For
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
      routes:
        # ------------------- Auth Service Start ------------------------------
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth-service/**
          filters:
            - RewritePath=/api/v1/auth-service/(?<segment>.*), /$\{segment}
            - JwtAuthFilter
        # ------------------- Auth Service End ------------------------------
---
spring:
  profiles:
    active: local
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: gateway
---
spring:
  profiles:
    active: test
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://lovebugs-config-server:8888
