server:
  port: 8000

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders:
              - Authorization
              - Credentials
              - Content-Type
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
              - X-Requested-With
              - X-Forwarded-For
              - X-Forwarded-Host
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE

      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth-service/auth/v1/**
          filters:
            - RewritePath=/api/auth-service/(?<segment>.*), /$\{segment}
            - CustomAccessTokenFilter

        - id: auth-server-admin
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth-service/admin/v1/**
          filters:
            - RewritePath=/api/auth-service/(?<segment>.*), /$\{segment}
            - CustomAccessTokenFilter

        - id: auth-server-public
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth-service/auth/v1/login
            - Path=/api/auth-service/auth/v1/signup
          filters:
            - RewritePath=/api/auth-service/(?<segment>.*), /$\{segment}


---
spring:
  profiles:
    active: local
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: gateway
---
spring:
  profiles:
    active: test
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://lovebugs-config-server:8888
